const COMPANY = 'Datalicious';
const APP = `${COMPANY} Mobile`;

export default {
  APP,
  COMPANY,
  BACK: 'Back',
  ENTER_EMAIL: 'Enter your email',
  ENTER_PWD: 'Enter your password',
  CHOOSE_PWD: 'Choose a password',
  CHOOSE_PWD_CONF: 'Confirm your password',
  LOGIN_ERR: 'Password Incorrect',
  PASSWORD: 'Password',
  WARNING: 'Warning',
  NEXT: 'Next',
  LOGIN: 'Log In',
  LOGIN_WITH: 'Log in with ',
  LOGGING_IN: 'Logging in...',
  SIGN_UP: 'Sign Up',
  LOGOUT: 'Log out',
  PWD_FORGOT: 'Forgot your password?',
  MODAL_RESET_PWD_TITLE: 'Password Recovery',
  MODAL_RESET_PWD_MSG: 'A link will be sent to the email you used to register that you can use to reset your password. Note: This will change your password for both web and mobile apps.',
  MODAL_RESET_PWD_SUCCESS: 'An email to reset your password has been sent to your email on file.',
  LOGOUT_CONF: 'Do you really wanna log out?',
  BIOM_FAILURE: 'Biometric Auth not enabled.',
  ENABLE: 'Enable',
  DISABLE: 'Disable',
  CONFIRM: 'Confirm',
  UPDATE: 'Update',
  DONE: 'Done',
  REVEAL: 'Reveal',
  HIDE: 'Hide',
  ERROR_TITLE: 'Something went wrong!',
  BEGIN: 'Begin',
  OK: 'OK',
  CANCEL: 'Cancel',
  SUCCESS: 'Success',
  ALERT: `Alert`,
  AMOUNT: 'Amount',
  RETURN: 'Return',
  RESET: 'Reset',
  APPROVE: 'Approve',
  REJECT: 'Reject',
  LOADING: 'Loading',
  ALLOW: 'Allow',
  DENY: 'Deny',
  MORE_OPTIONS: 'More Options',
  SETTINGS: 'Settings',
  GOTO_SETTINGS: 'Go to Settings',
  SECURITY: 'Security',
  ACCOUNT_VERIFICATION: 'Account Verification',
  PLACEHOLDER_USERNAME: 'Username',
  PLACEHOLDER_EMAIL: 'email',
  TOO_WEAK: 'Too weak',
  STRONG: 'Strong',
  PASSWORD_MUST_BE_8_CHARS: 'Password must be at least 8 characters',
  PASSWORDS_MATCH: 'Passwords match',
  PASSWORDS_MUST_MATCH: 'Passwords must match',
  RESET_BIOM: 'Reset Biometrics',
  ENABLE_BIOM: 'Enable Biometrics',
  DISABLE_BIOM: 'Disable Biometrics',
  ENABLE_FACE_ID: 'Enable Face ID',
  ENABLE_TOUCH_ID: 'Enable Touch ID',
  CHANGE_PWD: 'Change Password',
  MODAL_RESET_BIOM_MSG: `This will remove the biometric authentication settings and ask you to re-authorize on your next log in.`,
  MODAL_RESET_BIOM_SUCCESS: 'You will be asked to re-authorize upon your next successful log in.',
  MODAL_ENABLE_BIOM_MSG: 'This will enable biometric authentication for this application.',
  MODAL_ENABLE_BIOM_SUCCESS: 'Biometric Authentication Enabled',
  MODAL_DISABLE_BIOM_MSG: 'This will disable biometric authentication for this application. The application will stop asking you to authorize via fingerprint or face ID when you login with your username and password.',
  MODAL_DISABLE_BIOM_SUCCESS: 'Biometric Authentication Disabled',
  MODAL_UPDATE_VERIFICATION: `This will re-verify your account using all new information.`,
  TOS: 'Terms Of Service',
  I_AGREE: 'I agree',
  I_DO_THIS_LATER: 'I\'ll do this later',
  CREATED_AT:  'Created at',
  CLICK_AGREE: 'Click agree.',
  WELCOME_TO: `Welcome to`,
  VERIFY_EMAIL: 'Verify your email',
  FIRST_THINGS_FIRST: 'First things first',
  EMAIL_USED_TO_SIGN_UP: 'the address you used to sign up',
  RESEND_EMAIL: 'Re-send Email',
  STAND_BY: 'Please stand by',
  EMAIL_RESENT: 'Email Re-sent',
  MODAL_DEF_TITLE: `Confirm`,
  MODAL_DEF_MSG: `Perform this action?`,
  CLICK_BUTTON_ABOVE: `Select a Data File by clicking a button above.`,
  NO_DATA: `No Data`,
  ADD_TO_SET: `Add to set`,
  DATA_FOR: `Data For:`,
  MEAN: 'Mean',
  MEDIAN: 'Median',
  MODE: 'Mode',
  STD_DEV: 'Std Dev',
};
